# PasswOrd
version: '3'

services:
  ansible:
    build:
      context: .
      dockerfile: "Dockerfile-ansible"
    image: "ansible-host:latest"
    ports:
      - "2222:22"

  target1:
    build:
      context: .
      dockerfile: "Dockerfile"
    image: "ansible-targets:latest"

  target2:
    build:
      context: .
      dockerfile: "Dockerfile"
    image: "ansible-targets:latest"

  target3:
    build:
      context: .
      dockerfile: "Dockerfile"
    image: "ansible-targets:latest"
